language: go
sudo: required
dist: trusty
before_install:
  - sudo apt-get install -qq pkg-config fuse
  - sudo modprobe fuse
  - sudo chmod 666 /dev/fuse
  - sudo chown root:$USER /etc/fuse.conf

go:
    - "1.9.x"
    - "1.10.x"
    - master
